#cloud-config
write_files:
  - path: "/opt/aws/amazon-cloudwatch-agent.json"
    permissions: "0644"
    owner: "root"
    content: |
      {
          "agent": {
              "region": "${region}",
              "logfile": "/var/log/amazon-cloudwatch-agent.log",
              "metrics_collection_interval": 60
          },
          "metrics": {
              "namespace": "${cloudwatch_namespace}",
              "append_dimensions": {
                  "InstanceId": "$${aws:InstanceId}",
                  "AutoScalingGroupName": "$${aws:AutoScalingGroupName}"
              },
              "aggregation_dimensions": [
                  [
                      "InstanceId"
                  ],
                  [
                      "AutoScalingGroupName"
                  ]
              ],
              "metrics_collected": {
                  "disk": {
                      "resources": [
                          "*"
                      ],
                      "measurement": [
                          "disk_used_percent"
                      ]
                  },
                  "swap": {
                      "measurement": [
                          "swap_used_percent"
                      ]
                  },
                  "mem": {
                      "measurement": [
                          "mem_used_percent"
                      ]
                  }
              }
          },
          "logs": {
              "logs_collected": {
                  "files": {
                      "collect_list": [
                          {
                              "file_path": "/var/log/concourse.log*",
                              "log_group_name": "${log_group_name}",
                              "log_stream_name": "{instance_id}",
                              "timezone": "UTC"
                          }
                      ]
                  }
              },
              "log_stream_name": "{instance_id}/unknown-log-stream"
          }
      }
  - path: "/etc/systemd/system/node_exporter.service"
    permissions: "0644"
    owner: "root"
    content: |
      [Unit]
      Description=Node exporter for Prometheus to scrape
      Requires=network-online.target
      After=network-online.target

      [Service]
      Type=simple
      Restart=always
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
  - path: "/etc/systemd/system/concourse-logging.service"
    permissions: "0644"
    owner: "root"
    content: |
      [Unit]
      Description=Service for Concourse logging
      After=rc-local.service

      [Service]
      Type=simple
      Restart=always
      TimeoutSec=infinity

      ExecStart=/bin/bash -c '/usr/bin/journalctl -u concourse -f -o cat > /var/log/concourse.log'

      [Install]
      WantedBy=multi-user.target
  - path: "/etc/logrotate.d/concourse"
    permissions: "0644"
    owner: "root"
    content: |
      /var/log/concourse.log {
          create 0644 root root
          daily
          rotate 1
          size 100M
          postrotate
              systemctl restart concourse-logging awslogsd
          endscript
      }
runcmd:
  - |
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent.json
  - |
    systemctl enable concourse-logging.service --now
    systemctl enable amazon-cloudwatch-agent.service --now
    systemctl enable concourse.service --now
    %{if prometheus_enabled } systemctl enable node_exporter.service --now %{ endif }
